### ISSUE TITLE
Basic instructions don't work

### ISSUE THREAD

**Issue by brianmingus** [HarvardEconCS/turkserver-meteor#11]
Following the basic instructions isn't sufficient to get the `/turkserver` route working.

<pre>
meteor create someapp
cd someapp 
git clone --recursive https://github.com:HarvardEconCS/turkserver-meteor.git packages/turkserver
mrt update turkserver
meteor
</pre>

The first issue seems to be that running `mrt update turkserver` from the someapp directory does nothing, however, running it from the turkserver directory does.

**Comment by bluepuma77** [comment]
I wold like to add to "Basic instructions don't work".

I installed `turkserver-meteor` according to the latest docs on GitHub:
```
meteor create my-turkserver
cd my-turkserver/
git clone --recursive https://github.com/HarvardEconCS/turkserver-meteor.git packages/mizzao:turkserver
meteor add mizzao:turkserver
meteor
```
Then I get the error message:
```
Missing Amazon API keys for connecting to MTurk. Please configure.
No admin password found for Turkserver. Please configure it in your settings.
```
It would be great to explain directly in the "Quick Start" where that file should be and what the contents should look like, otherwise there is just no real "Quick Start" of the application.

**Comment by bluepuma77** [comment]
Create a settings file `settings.json` in the app directory with following content
```
{
    "turkserver": {
        "adminPassword": "something",
        "hits": {
            "acceptUnknownHits": true
        },
        "mturk": {
            "accessKeyId": "Your_AWS_Access_Key",
            "secretAccessKey": "Your_AWS_Secret_Key"
        }
    }
}
```
and start the application with `meteor run --settings settings.json`

**Comment by ldworkin** [comment]
Hi @bluepuma77 -- you might try looking at the following tutorial I wrote for TurkServer [here](http://ldworkin.github.io/turkserver-tutorial/). I give a much slower step-by-step introduction there, including an explanation of what you've noticed above :) Let me know if you have any questions about it!

**Comment by mizzao** [comment]
Thanks @ldworkin.

@bluepuma77, I'm going to update the readme and docs to point to @ldworkin's tutorial; just haven't gotten around to it yet. Please let us know if you have any questions!
