### ISSUE TITLE
Continued confusion about install

### ISSUE THREAD

**Issue by LeMasters** [HarvardEconCS/turkserver-meteor#16]
Meteor is getting easier to use.  The elimination of meteorite was a real blessing.  But this has left a lot of apps' docs in (even greater) shambles (than before), in particular with regard to the "installation instructions."

As they exist, the step-by-step instructions for the current version of *turkserver-meteor* do not work.  There are a few "help me" threads that contain fixes, but those all continue to refer to *mrt*.  This framework is clearly going to be invaluable to our work, but only once we actually get it to run.

Could you glance at those instructions, looking for the one or two tiny details that have been omitted, and point us in the right direction?

Thanks for (what looks to be) amazing work on this.
Garrison

**Comment by mizzao** [comment]
Sorry for the delayed response as I was on vacation.

I will try to update the documentation for this once I start my new position next week. Also, I would love to have a call on Skype or something just to chat about the grander scheme of doing online experiments, and understand how I can help with what you guys are trying to do.

**Comment by mizzao** [comment]
Hey @LeMasters, what error are you getting when you try to add the package to a Meteor app?

Also, I'm actively updating documentation at http://turkserver.meteor.com/. When that is close to done, I'll publish the package so that it can be installed directly by Meteor.

**Comment by mizzao** [comment]
Hi @LeMasters, I'm not sure what trouble you are having installing turkserver in your Meteor app but they appear to work fine. Also, the documentation at http://turkserver.meteor.com/ is growing by the week.

Cheers,
Andrew

**Comment by mizzao** [comment]
Please see http://ldworkin.github.io/turkserver-tutorial/ for a much more definitive guide on how to use TurkServer.
