### ISSUE TITLE
Can't Run the Example

### ISSUE THREAD

**Issue by zhitaoyin** [HarvardEconCS/turkserver-meteor#17]
Hi Andrew,

I tried to run the [CrowdMapper](https://github.com/mizzao/CrowdMapper), the example you included in the tutorial. 

```
meteor --settings settings.json
```

However, I got an error.

```
Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/."
```
The TurkServer seems working well.

<img width="1402" alt="screen shot 2015-07-08 at 10 01 48 pm" src="https://cloud.githubusercontent.com/assets/8290950/8586492/13be6f7c-25bd-11e5-86a2-d457973ae785.png">

Could you give me any cues to address this issue?

Thanks,
Zhitao

**Comment by mizzao** [comment]
What link did you visit that produced that error?

The CrowdMapper example is pretty complex and probably hard to learn from. I am in the process of cleaning up the code and writing API documentation which is slowly appearing at http://turkserver.meteor.com/. This should help quite a bit for others to get started.

**Comment by zhitaoyin** [comment]
I got the error when I visited http://localhost:3000

**Comment by mizzao** [comment]
http://ldworkin.github.io/turkserver-tutorial/ is a much better way to get started with using this now. Please take a look!
