### ISSUE TITLE
Publish assignment for duration of a task

### ISSUE THREAD

**Issue by mizzao** [HarvardEconCS/turkserver-meteor#29]
Currently, assignment information is published just with instances. Having it published over the entire course of a HIT/task would allow for

- Reading assignment data (like bonus) in the exit survey
- Avoiding a wasteful subscribe/resubscribe when many instances are used over the lifetime of a task

Changes in https://github.com/HarvardEconCS/turkserver-meteor/blob/master/lib/turkserver.coffee

**Comment by ldworkin** [comment]
Was going to fix this by moving lines 125-135 of turkserver.coffee up to the previous publish block (is that the right thing to do?) , but then realized I don't understand the point of [line 128](https://github.com/HarvardEconCS/turkserver-meteor/blob/master/lib/turkserver.coffee#L128). Would this work? https://gist.github.com/ldworkin/f9403bd3b6d375e55aad

**Comment by mizzao** [comment]
Yeah, line 128 is basically a no-op. It was going to use http://docs.mongodb.org/manual/reference/operator/projection/elemMatch/ but turns out that is not supported yet in Meteor (https://github.com/meteor/meteor/blob/devel/packages/minimongo/projection.js#L170).

Moving it up to the previous publish block and adding `status: "assigned"` would do, I think - as long as we don't ever have a case where someone might be doing two assignments simultaneously.

**Comment by ldworkin** [comment]
Hmm, right. I guess that could happen. Then both assignments would get published and the client would have to figure it out, which is maybe not the end of the world. Or is there an easy way to look up current HIT id on server side (like from the query parameters) and only send over the matching assignment?

**Comment by mizzao** [comment]
I think it's OK to assume 1 assignment at a time for now, and if we have 2 on the client we can either figure it out or show some warning.

I just remembered that we `Turkserver.Assignment.getCurrentUserAssignment` which makes the same assumption, so I think that would be fine.

**Comment by ldworkin** [comment]
Ok, in that case, see here:

4dfd5f748747f93a8fd3bf644c5f7fd52a2a9f14

**Comment by mizzao** [comment]
Great, this saves both a database call and setting up a live query for every user-added-to-instance and seems to have made the lobby clear out significantly faster today.
