### ISSUE TITLE
E-mail workers in response to exit survey comments

### ISSUE THREAD

**Issue by mizzao** [HarvardEconCS/turkserver-meteor#32]
One click message sending would help us respond to questions in the exit survey.

**Comment by ldworkin** [comment]
See e913aa609440b64c2e98c56b53743049fe4da667, and tested on sandbox!

**Comment by mizzao** [comment]
Looks great! We're now 200% spammier!

Jokes aside, this will make it much easier to contact workers if we think something weird has happened to them.
