### ISSUE TITLE
Missing documentation for basic setup and hosting.

### ISSUE THREAD

**Issue by infiniteline** [HarvardEconCS/turkserver-meteor#34]
I've looked around, but there doesn't seem to be any documentation on basic project setup and workflow for integrating directly with Mechanical Turk. The Crowd Mapper project is really a bit dense to try to parse through and figure out a beginning workflow. Does something like this exist? If you can provide me with a real good starting point, I'd be happy to produce some documentation to help others that might be looking to work with TurkServer-Meteor.

**Comment by mizzao** [comment]
Hi @infiniteline, thanks for writing and apologies for the state of the current documentation.

I'm currently working on a project with @ldworkin which is quite a bit simpler to parse, https://github.com/ldworkin/meteor-prisoners-dilemma. The user interface is quite simple but it definitely uses most of the powerful features of turkserver.

@ldworkin and I will work on getting some better getting started documentation out and available soon, once this experiment deployment is finished.

**Comment by infiniteline** [comment]
Thanks so much! I'll take a look further through that project and see what I can find out. Just briefly, I already see that there are some object methods that I haven't seen before. Please let me know if there's something I can do to help.

**Comment by mizzao** [comment]
@infiniteline Have you looked at http://turkserver.meteor.com/ at all? It might help fill in some of the gaps.

**Comment by infiniteline** [comment]
Hi @mizzao. Yes, I definitely have, but it seems like there are some missing events (?). The problems I haven't been able to address are:
- How do I set the ad page for the HIT?
- How does my project know when a worker has accepted the HIT?
- How do I send the worker back to Mechanical Turk at the end of the experiment?

**Comment by mizzao** [comment]
@infiniteline It sounds like you have been using something like PsiTurk, so I don't know if the terminology fits. TurkServer lets you build an app that runs in the MTurk iframe, so there is no "ad page" nor "sending the worker back to Mechanical Turk". When a worker accepts the HIT, they show up as online in the admin console automatically, and your code decides what they see.

**Comment by infiniteline** [comment]
Yes, definitely comping over from the PsiTurk end of things. So the worker accepts a HIT and they automatically show up in the lobby? Thanks for making it so easy!  ;)

I briefly looked though the sample project and I'll run it now to see the workflow. Thanks again for your help @mizzao.

**Comment by ldworkin** [comment]
Hey @infiniteline -- I'm currently working on writing a tutorial for TurkServer -- I had been putting it off, but your question inspired me to start last night :) @mizzao has built an awesome framework, but I absolutely know how tricky it is to figure out how all the parts fit together and what the workflow should be from start to finish. Don't know what your timeframe is, but I should be done with the tutorial within, say, a week, and I think it could be a very big help to you!

**Comment by infiniteline** [comment]
@ldworkin Thanks Lili. That sounds great! Let me know if I can help.

**Comment by mizzao** [comment]
FYI, the tutorial is currently at http://lilianne.me/turkserver/, but I imagine we'll find a way to put it on GitHub after a bit so that we can collaboratively improve it.
