### ISSUE TITLE
Sort list of created HITs in descending order

### ISSUE THREAD

**Issue by mizzao** [HarvardEconCS/turkserver-meteor#35]
Also replace janky table with reactive-table where possible.

**Comment by ldworkin** [comment]
Sorting done in ba0905a5c8d0d57478c891ecf7dc2bc6a8f6716a, but only problem is CreationTime is not set until refresh, so before a refresh the HIT goes to the bottom of the list. Would it break anything to set a default CreationTime as current datetime when the "create HIT" button is pressed? Then upon refresh it would get overridden with Turk's creation time?

**Comment by mizzao** [comment]
70ebdf54fa2e413215872b9a53a6c0abd0c8f1e8 refreshes right after a creation so we should be all set.
