### ISSUE TITLE
Add a "get batch by name" method

### ISSUE THREAD

**Issue by ldworkin** [HarvardEconCS/turkserver-meteor#36]
Avoid the need to query Mongo with `var batchId = Batches.findOne({name: "batchName"})._id` before using any Batches API method. Better to have it all within the API when possible. (Occurred to me when writing the tutorial.)

**Comment by ldworkin** [comment]
Added in f3bfcdfee21a1d9082a0946bd7803241411949f7 -- if it looks okay, cherry pick?

**Comment by mizzao** [comment]
Yeah, that looks fine. In fact, I'm happy if you just take out the watch button completely and just rely on the "data route" functionality that you are starting; I don't think the watch functionality is particularly useful and this is a better way to do it.

Then I could just merge your branch back into `master`.

**Comment by ldworkin** [comment]
Sure, that sounds good. I didn't want to remove your watch route entirely (you never know, you might want it for v2 of Crisis Mapping), so right now the interface shows a "data" and/or "watch" button depending on whether you have dataRoute and/or watchRoute defined in settings.json. But I think there's something intermittently wonky about how the subscriptions for the dataRoute work, so maybe I'll run that by you later before we merge.

**Comment by mizzao** [comment]
I don't use the watch button for Crisis Mapping either. I also have a "dataRoute" :D

The watch button puts the admin in a partition so basically none of the other admin functions work; hence I don't think it's a very good design. It was just a first-stab attempt.

**Comment by ldworkin** [comment]
Watching has been killed in 8e48cb84117dca1f1aef671d3cb7904802dbd26c. Dijsktra would be [proud](http://discuss.fogcreek.com/joelonsoftware/default.asp?cmd=show&ixPost=8665). 

Anything else we want for the new dataRoute? Else I think this branch is ready to be merged.

**Comment by mizzao** [comment]
Looks great! Thanks for all that cleanup you did, that code was clearly a mess anyway (i.e. the two `Router.go` calls.)
