### ISSUE TITLE
Add RequiredToPreview to table for creating qualifications

### ISSUE THREAD

**Issue by mizzao** [HarvardEconCS/turkserver-meteor#38]
http://docs.aws.amazon.com/AWSMechTurk/latest/AWSMturkAPI/ApiReference_QualificationRequirementDataStructureArticle.html

**Comment by mizzao** [comment]
We actually don't have an API for creating qualifications directly through TurkServer right now. A neat feature would be to import qualifications from MTurk directly into the app and also create new ones that allow the `RequiredToPreview` option.

Not at all required, just something to do for the future.

**Comment by ldworkin** [comment]
Wait, the RequiredToPreview field is on the *qualification requirement*, not the *qualification type* -- so we actually do want it in the table for creating qualification requirements, right?

**Comment by mizzao** [comment]
oic, yeah then I guess it should be shown in the table :)

I do remember making that table a long time ago and thinking "there's no way we'll need this, I'm just going to skip it".

No extra code in the MTurk API is needed, see for example https://github.com/jefftimesten/mturk/blob/master/index.js#L51

**Comment by ldworkin** [comment]
Yup sounds good -- I'll take a stab on the experimental branch first.

**Comment by ldworkin** [comment]
Is this sufficient? 12b0502bb7bbb8c83c5081fdd09a8cfbc37a80bd 

Still need to test on sandbox.

**Comment by mizzao** [comment]
This works, right? Closing the issue.
