### ISSUE TITLE
Add buttons to approve assignments and pay bonuses

### ISSUE THREAD

**Issue by ldworkin** [HarvardEconCS/turkserver-meteor#39]
Add buttons to the Assignments - Completed page to approve all assignments and pay all bonus. These would just be UI wrappers around Assignment.approve and Assignment.payBonus, but would be automatically called on every completed assignment in the current batch. Should probably have a "warning" popup that tells you how many workers would be affected, and how much it would cost, and then lets you confirm.

**Comment by mizzao** [comment]
Nice, good idea. It could also refresh assignments beforehand to ensure that they are in the `Submitted` state before paying.
