### ISSUE TITLE
Unintuitive controls for deselecting current HIT to create a new HIT

### ISSUE THREAD

**Issue by ejolly** [HarvardEconCS/turkserver-meteor#43]
There's seems to be an issue when trying to create a a new HIT from the HITs menu in the admin interface such that, if you click on an outstanding HIT then click away, the "Create New HIT" dialogue box fails to appear. It only seem to reappear when logging out of the admin interface, refreshing, and logging back in. It will appear initially *before* clicking on an outstanding HIT.

**Comment by mizzao** [comment]
Yeah, this is a bit janky right now. To make it go away, just click the title bar of the HIT table. Agreed that there should be a better way to clear the selected HIT.

**Comment by ldworkin** [comment]
Just to clarify, right now the way to make the "Create New HIT" dialogue come back is to click the first row of the table, i.e.: https://www.dropbox.com/s/ccbcc7c2nl2hnxc/hit_bar.png?dl=0

But I'll fix this today!

**Comment by ldworkin** [comment]
Fixed in experimental branch here: 82cb752d92b8ca2f73cbe8bdcf2499b219e7b8ed
