### ISSUE TITLE
User login issues with new version of partitioner

### ISSUE THREAD

**Issue by mizzao** [HarvardEconCS/turkserver-meteor#44]
This came up during testing. The fix for mizzao/meteor-partitioner#13, committed in 0.5.7 causes a weird issue where HIT logins throw a partitioner error due to the way collection-hooks retrieve docs after an update.

This can be replicated by simply reloading a tab that is running a turkserver Tinytest with `mizzao:partitioner@0.5.7`. Need to think about the best way to fix this.

**Comment by ejolly** [comment]
Just curious if there was any update on this, or is the suggested temp fix in #52 (i.e. forcing `mizzao:partitioner@0.5.6`) the current best option?

**Comment by mizzao** [comment]
Yeah, using `mizzao:partitioner@0.5.6` is the best choice until we figure out the right workaround.

It's a rather complex interaction between Meteor accounts, collection hooks, and partitioner. I think I'm going to just have all `_id: { $in: ...}` queries ignore partitioning.

**Comment by mizzao** [comment]
`mizzao:partitioner@0.5.8` has a workaround for this now, as I described ^.
