### ISSUE TITLE
No route on the client or the server for url

### ISSUE THREAD

**Issue by ZJoveski** [HarvardEconCS/turkserver-meteor#46]
It seems to me that this is more of an <code>iron-router</code> and not a TurkServer issue, but I could really use some help. I have a collection <code>Recruitng</code> and when I query it on the client side within a template helper, there seems to be no problem. For example, the following works perfectly fine.

    Template.lobbyRecruiting.helpers({
        active: function() {
            var obj = Recruiting.findOne();
            // calculate and return something
        }
    });
But, if I include code (again, on the client side) like

    Tracker.autorun( function() {
        var obj = Recruiting.findOne();
        // do something
    });
or 

    Recruiting.find().observeChanges({
        added: function(id) {
            // do something
        }
    });

then the following template 

    "Oops, looks like there's no route on the client 
    or the server for url: "http://myapp.meteor.com/some_route." 

gets shown for every <code>some_route</code> that I have defined.

What's interesting is that the TurkServer routes (<code>http://myapp.meteor.com/turkserver/</code>) continue to work without any problems. Also, I do not get any errors on the server side. And it's worth mentioning that the <code>Recruiting</code> collection is not being partitioned. But since I was able to query it and retrieve the needed data within template helpers, I don't think this is the problem.

Any help would be greatly appreciated!

**Comment by ZJoveski** [comment]
It turns out I was looking for the error in the wrong place. I've messed up the organization of files and so when the <code>Tracker.autorun</code> block was first executed, the file containing the collection definition wasn't loaded yet, which led to an exception being thrown and apparently if this happens in a <code>Tracker.autorun</code> block the computation is stopped and is not rerun again (see http://stackoverflow.com/questions/22217373/meteor-deps-autorun-doesnt-get-triggerd-whats-its-use-compared-to-observe). I realize now that it is not a TurkServer issue at all, so it might be better to delete it entirely. What do you think @mizzao?

**Comment by mizzao** [comment]
Yep, that sounds about right.
