### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by mohsenmosleh** [HarvardEconCS/turkserver-meteor#50]
I receive the following error when I want to add TurkServer package to my app.

meteor add mizzao:turkserver
 => Errors while adding packages:             
                                              
While selecting package versions:
error: Conflict: Constraint stylus@1.0.7 is not satisfied by stylus 2.511.0_1.
Constraints on package "stylus":
* stylus@=2.511.0_1 <- top level
* stylus@1.0.7 <- mizzao:turkserver 0.0.0

**Comment by mizzao** [comment]
Meteor 1.2 was just released today. Any chance you were trying it on that?

I haven't tested on 1.2 and will fix this shortly. In the meantime you should try and use 1.1.0.3.

**Comment by mohsenmosleh** [comment]
You are right, I received this error after upgrading meteor this morning. How can I downgrade meteor?

**Comment by mizzao** [comment]
You can do `meteor update --release 1.1.0.3`.

However, I will be fixing this shortly to make sure it works with Meteor 1.2.

**Comment by mizzao** [comment]
The latest commit should now work with Meteor 1.2.
