### ISSUE TITLE
Passing arguments to Partitioner.directOperation

### ISSUE THREAD

**Issue by ejolly** [HarvardEconCS/turkserver-meteor#51]
I'm trying to pass in an argument to the function executed by Partitioner.directOperation but it doesn't seem to be working. Am I incorrectly specifying this or is that not currently possible? This doesn't seem to work and results in nothing being returned: 

    var userName = 'Me'
    Partitioner.directOperation(function(userName){
        return Database.findOne({"User":userName});
    });
And just to make sure I'm not messing up a mongo db query, the following two don't work either:

    var userName = 'Me'
    Partitioner.directOperation(function(userName){
        console.log(userName); //returns undefined
    });
    
    var userName = 'Me'
    //Produces TypeError: string is not a function
    Partitioner.directOperation(userName, function(){
        console.log(userName); 
    });

The actual context is a Client that makes a `Meteor.call('someMethod', Meteor.userId())` during the exit survey. Because they no longer have access to the partitioned collection I setup for the main experiment (because they're in the exit survey) I'm instead doing a server side collection lookup based on their Meteor user ID, hence the need to pass their id to `Partitioner.directOperation`

**Comment by mizzao** [comment]
The following should work:

```
var userName = 'Me';
Partitioner.directOperation(function() {
    return Database.findOne({"User": userName});
});
```

You were defining a closure in the function that hid the original `userName`. You should read about function closures in Javascript work: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Closures
