### ISSUE TITLE
TurkServer now requires Meteor 1.2

### ISSUE THREAD

**Issue by marsplus** [HarvardEconCS/turkserver-meteor#53]
Hi people, 

Recently I am not being able to install turkserver successfully. I followed the instructions, first I git clone the repo, then I executed the command: 

meteor add mizzao:turkserver

an error appears as:

<img width="570" alt="screen shot 2015-10-02 at 16 36 36" src="https://cloud.githubusercontent.com/assets/1840631/10258505/57273de8-6924-11e5-9bf5-9c05930d759b.png">

Previously, I could not only successfully install turkserver, but also deploy apps using turkserver on meteor.com. 

Here is package info of my app:
meteor-platform
accounts-ui
accounts-password
benjaminrh:event-hooks
accounts-base
mizzao:user-status
sgi:sprintfjs
momentjs:moment
npm-bcrypt
iron:router
mizzao:turkserver
coffeescript
mizzao:partitioner
underscore
twbs:bootstrap
d3js:d3
d3
grigio:babel
sacha:spin
matb33:bootstrap-progress-bars
meteorhacks:kadira
peppelg:on-login-logout
cfs:standard-packages
cfs:filesystem
mquandalle:bower

===============================================================

Here is version info of my app:
accounts-base@1.2.0
accounts-password@1.1.1
accounts-ui@1.1.5
accounts-ui-unstyled@1.1.7
aldeed:template-extension@3.4.3
autoupdate@1.2.1
base64@1.0.3
benjaminrh:event-hooks@1.4.3
binary-heap@1.0.3
blaze@2.1.2
blaze-tools@1.0.3
boilerplate-generator@1.0.3
callback-hook@1.0.3
cfs:access-point@0.1.49
cfs:base-package@0.0.30
cfs:collection@0.5.5
cfs:collection-filters@0.2.4
cfs:data-man@0.0.6
cfs:file@0.1.17
cfs:filesystem@0.1.2
cfs:http-methods@0.0.29
cfs:http-publish@0.0.13
cfs:power-queue@0.9.11
cfs:reactive-list@0.0.9
cfs:reactive-property@0.0.4
cfs:standard-packages@0.5.9
cfs:storage-adapter@0.2.2
cfs:tempstore@0.1.5
cfs:upload-http@0.0.20
cfs:worker@0.1.4
check@1.0.5
coffeescript@1.0.6
d3@1.0.0
d3js:d3@3.5.5
dandv:caret-position@2.1.1
ddp@1.1.0
deps@1.0.7
ejson@1.0.6
email@1.0.6
facts@1.0.4
fastclick@1.0.3
geojson-utils@1.0.3
grigio:babel@0.1.4
html-tools@1.0.4
htmljs@1.0.4
http@1.1.0
id-map@1.0.3

**Comment by mizzao** [comment]
The latest commit in the git repo depends on Meteor 1.2. You should run the following command, and read the release notes;

```
meteor update --release 1.2.0.2
```

Note that this may cause other breakage in your app so you should make sure everything is working before running as production.
