### ISSUE TITLE
The link to the tutorial seems to be broken

### ISSUE THREAD

**Issue by DanielTakeshi** [HarvardEconCS/turkserver-meteor#57]
Tutorial link: http://ldworkin.github.io/turkserver-tutorial/

Right now it results in a page not found. I can find the tutorial with the cache, but I just wanted to let you know that it was down.

**Comment by mizzao** [comment]
Moved to http://virtuallab.github.io/.

Where did you find that link? I will update it.

**Comment by DanielTakeshi** [comment]
Thanks. It;s when you say

TurkServer is currently still in development, but we have an in-depth tutorial available with an accompanying example app. 

on the github homepage.

**Comment by mizzao** [comment]
Great. Just curious, what are you interested in this for and what kind of project are you working on?

**Comment by DanielTakeshi** [comment]
It is for a project about Atari games. This [Nature 2015 paper](http://www.nature.com/nature/journal/v518/n7540/full/nature14236.html) talks about deep reinforcement learning for AI agents to play Atari games. So we can use this to run a Mechanical Turk experiment where players play Atari games for comparison purposes, etc.
